# Generated by Django 4.2.30 on 2026-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bus', 'Автобус'), ('plane', 'Самолет'), ('ferry', 'Речной транспорт'), ('train', 'Поезд')], max_length=20)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
