# Generated by Django 4.2.30 on 2026-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_transport_event_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='city',
            field=models.CharField(default='Ханты-Мансийск', max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('bus', 'Автобус'), ('shuttle', 'Маршрутка'), ('train', 'Электричка'), ('taxi', 'Такси')], max_length=20),
        ),
    ]
