# Generated by Django 4.2.30 on 2026-04-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_transport_city_alter_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='route_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='stops',
            field=models.TextField(blank=True, null=True),
        ),
    ]
